### PR TITLE
[WIP] Add support for Waymo Real-time Model

### PR DESCRIPTION
**Pull request by tianweiy**
This pull request aims to add support for our CenterPoint-RT model.

### CODE REVIEW

**Comment by YoushaaMurhij** [comment]
Thanks for updating your baseline.
I was trying the new dynamic voxel encoder but `scatter_mean` is missing.
`ModuleNotFoundError: No module named 'det3d.core.utils.scatter'`
Could you please add it to this branch?

**Comment by tianweiy** [comment]
see below. The code is copied from pytorch_scatter. You can directly install it if you use newer pytorch version. I need to modify it a little bit to fit torch 1.1. 

The new baseline is not ready yet. I will gradually move those modifications to these repo. 

```
# The following code are copied from pytorch_scatter https://github.com/rusty1s/pytorch_scatter
# Copyright (c) 2020 Matthias Fey <matthias.fey@tu-dortmund.de>
# MIT License 
from typing import Optional, Tuple
import torch 

@torch.jit.script
def broadcast(src: torch.Tensor, other: torch.Tensor, dim: int):
    if dim < 0:
        dim = other.dim() + dim
    if src.dim() == 1:
        for _ in range(dim):
            src = src.unsqueeze(0)
    for _ in range(other.dim()-src.dim()):
        src = src.unsqueeze(-1)
    src = src.expand_as(other)
    return src

@torch.jit.script
def scatter_sum(src: torch.Tensor, index: torch.Tensor, dim: int = -1,
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    index = broadcast(index, src, dim)
    if out is None:
        size = list(src.size())
        if dim_size is not None:
            size[dim] = dim_size
        elif index.numel() == 0:
            size[dim] = 0
        else:
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
    else:
        return out.scatter_add_(dim, index, src)

@torch.jit.script
def scatter_mean(src: torch.Tensor, index: torch.Tensor, dim: int = -1,
                 out: Optional[torch.Tensor] = None,
                 dim_size: Optional[int] = None) -> torch.Tensor:

    out = scatter_sum(src, index, dim, out, dim_size)
    dim_size = out.size(dim)

    index_dim = dim
    if index_dim < 0:
        index_dim = index_dim + src.dim()
    if index.dim() <= index_dim:
        index_dim = index.dim() - 1

    ones = torch.ones(index.size(), dtype=src.dtype, device=src.device)
    count = scatter_sum(ones, index, index_dim, None, dim_size)
    count.clamp_(1)
    count = broadcast(count, out, dim)
    if torch.is_floating_point(out):
        out.div_(count)
    else:
        assert 0 
        # out.floor_divide_(count)
    return out

```

**Comment by YoushaaMurhij** [comment]
Thank you!
I think there is still minor errors in voxelization function: * instead of &  and :
```
line 9, in voxelization
    keep = (points[:, 0] >= pc_range[0]) & (points[:, 0] <= pc_range[3]) & \
IndexError: too many indices for array
```

**Comment by tianweiy** [comment]
points is a list of tensor and each tensor is N x C  dimension

**Comment by YoushaaMurhij** [comment]
@tianweiy , I am confused now. In [simple_inferernce_waymo.py](https://github.com/tianweiy/CenterPoint/blob/4a6e9abfc4a60764dd71ab3185de504f57883905/tools/simple_inference_waymo.py#L2) I used to provide a list of points as an input to the spconv.utils.VoxelGenerator with shape [N,6] or [N,5]. But now I want to replace VoxelGenerator with the new [ dynamic_voxel_encoder.py](https://github.com/tianweiy/CenterPoint/blob/new_release/det3d/models/readers/dynamic_voxel_encoder.py). I am not sure how to get the current new input shape (list of tensor) from the old one. Am I missing another prepressing step?

Thanks!

**Comment by tianweiy** [comment]
This is mainly for batch training. For single object just do points = [points]

**Comment by tianweiy** [comment]
Here is the code I used for waymo submission. 

```
from det3d.torchie.trainer import load_checkpoint
from det3d.models import build_detector
from det3d.core.utils.scatter import scatter_mean
from det3d.torchie import Config
import numpy as np
import torch
import time 

def test_time(func):
    def inner(*args, **kwargs):
        torch.cuda.synchronize()
        tic = time.perf_counter()
        data_dict = func(*args, **kwargs)
        torch.cuda.synchronize()
        print(time.perf_counter()-tic)
        return data_dict 

    return inner 

MODEL_CFG_PATH = '/code/CenterPoint-dev/configs/waymo/voxelnet/two_stage/waymo_base.py'
MODEL_WEIGHTS = '/code/CenterPoint-dev/models/final_model_train.pth'

LIDAR_NAMES = ['TOP']
LIDAR_FIELDS = ['RANGE_IMAGE_FIRST_RETURN', 'RANGE_IMAGE_SECOND_RETURN'] # , 

DATA_FIELDS = [] 
for lidar_field in LIDAR_FIELDS:
    for lidar_name in LIDAR_NAMES:
        for suffix in ['', '_1', '_2']:
            DATA_FIELDS.append(lidar_name + '_' + lidar_field + suffix)

DATA_FIELDS += ['POSE', 'POSE_1', 'POSE_2', 'TIMESTAMP', 'TIMESTAMP_1', 'TIMESTAMP_2', ]
model = None

def initialize_model():
    global model, voxel_generator  
    cfg = Config.fromfile(MODEL_CFG_PATH)
    model = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
    
    load_checkpoint(model, MODEL_WEIGHTS, map_location="cpu", strict=True)

    model.single_det.backbone = model.single_det.backbone.half()
    model.single_det.neck = model.single_det.neck.half()

    model = model.cuda()
    model.eval()

    # init memory pool 
    expected_memory = 1e9 * 8 
    pool = torch.zeros(int(expected_memory/4)).cuda()
    del pool

def voxelization(points, pc_range, voxel_size):    
    keep = (points[:, 0] >= pc_range[0]) * (points[:, 0] <= pc_range[3]) * \
        (points[:, 1] >= pc_range[1]) * (points[:, 1] <= pc_range[4]) * \
            (points[:, 2] >= pc_range[2]) * (points[:, 2] <= pc_range[5])
    points = points[keep, :]    
    coords = ((points[:, [2, 1, 0]] - pc_range[[2, 1, 0]]) /  voxel_size[[2, 1, 0]]).to(torch.int64)
    unique_coords, inverse_indices = coords.unique(return_inverse=True, dim=0)

    voxels = scatter_mean(points, inverse_indices, dim=0)
    return voxels, unique_coords

def transform_point_cloud(pc, old_pose, new_pose):
    """Transform a point cloud from one vehicle frame to another.
    Args:
    pc: N x 6 float32 point cloud, where the final three dimensions are the
        cartesian coordinates of the points in the old vehicle frame.
    old_pose: 4 x 4 float32 vehicle pose at the timestamp of the point cloud
    new_pose: 4 x 4 float32 vehicle pose to transform the point cloud to.
    """
    # Extract the 3x3 rotation matrices and 3x1 translation vectors from the
    # old and new poses.
    # (3, 3)
    old_rot = old_pose[:3, :3]
    # (3, 1)
    old_trans = old_pose[:3, 3:4]
    # (3, 3)
    new_rot = new_pose[:3, :3]
    # (3, 1)
    new_trans = new_pose[:3, 3:4]

    # Extract the local cartesian coordinates from the N x 6 point cloud, adding
    # a new axis at the end to work with np.matmul.
    # (N, 3, 1)
    local_cartesian_coords = pc[..., :3][..., None]

    # Transform the points from local coordinates to global using the old pose.
    # (N, 3, 1)
    global_coords = old_rot @ local_cartesian_coords + old_trans

    # Transform the points from global coordinates to the new local coordinates
    # using the new pose.
    # (N, 3, 1)
    new_local = new_rot.transpose(1, 0) @ (global_coords - new_trans)

    # Reassign the dimensions of the range image with the cartesian coordinates
    # in
    pc[..., :3] = new_local[..., 0]

def _process_inputs(input_sensor_dict):
    point_clouds = [] 
    device = 'cuda'
    newest_pose = torch.tensor(input_sensor_dict['POSE'], dtype=torch.float32, device=device)

    cur_time = input_sensor_dict['TIMESTAMP']
    for suffix in ['','_1', '_2']: 
        P = [] 
        for field in ['TOP_RANGE_IMAGE_FIRST_RETURN', 'TOP_RANGE_IMAGE_SECOND_RETURN']:
            # H x W x 6
            lidar_range_image = torch.tensor(input_sensor_dict[field+suffix], dtype=torch.float32, device=device)
            # Flatten and select all points with positive range.
            point_cloud = lidar_range_image[lidar_range_image[..., 0] > 0, :]
            P.append(point_cloud)

        P = torch.cat(P, dim=0)
        P = P[:, [3, 4, 5, 1, 2]]

        if suffix != '':
            src_pose = torch.tensor(input_sensor_dict['POSE' + suffix], dtype=torch.float32, device=device)
            transform_point_cloud(P, src_pose, newest_pose)

        time_lag = (cur_time - input_sensor_dict['TIMESTAMP'+suffix]) * 1e-6     
        P[:, 3] = torch.tanh(P[:, 3])
        P = torch.cat([P, P.new_ones((P.shape[0], 1)) * time_lag], dim=1)
        point_clouds.append(P)
    points = torch.cat(point_clouds, dim=0)

    # first step voxelization
    # force it to be fp32 to avoid numerical issue during voxelization
    # points = torch.tensor(points, dtype=torch.float32, device=device)
    pc_range = torch.tensor([-75.2, -75.2, -2, 75.2, 75.2, 4], 
        dtype=torch.float32, device=device)
    voxel_size = torch.tensor([0.1, 0.1, 0.15], 
        dtype=torch.float32, device=device)

    voxels, coords = voxelization(points, pc_range, voxel_size)
    
    voxels = voxels.half()
    coords = coords.half()

    coords = torch.cat([coords.new_zeros(coords.shape[0], 1), coords], dim=1)

    inputs = dict(
            voxels=voxels,
            coors=coords,
            input_shape=np.array([1504, 1504, 40], dtype=np.int32),
            batch_size=1
        )
    return inputs 

def run_model(**kwargs):
    with torch.no_grad():
        data_dict = _process_inputs(kwargs)
        outputs = model(data_dict, return_loss=False, use_final_feature=True)[0]

        boxes = outputs['box3d_lidar']
        classes = outputs['label_preds']

        boxes[:, -1] = -boxes[:, -1] - np.pi / 2
        boxes = boxes[:, [0, 1, 2, 4, 3, 5, -1]]

        classes += 1 
        classes[classes == 3] = 4 

        return {'boxes': boxes.cpu().numpy(),
            'scores': outputs['scores'].cpu().numpy(),
            'classes': classes.cpu().numpy()}


```

**Comment by YoushaaMurhij** [comment]
@tianweiy, Is this pr complete now? I want to train and try this real time model.
Thanks!

**Comment by tianweiy** [comment]
Hi, I haven't tested it yet. But it should be near complete. You can try this config in the new_release branch

https://github.com/tianweiy/CenterPoint/blob/new_release/configs/waymo/voxelnet/waymo_centerpoint_voxelnet_three_sweeps_20e_iou_pred.py 

I can help if you get any hard to fix error/bug

I am not working on 3d det these few months so it will take me some time to fully test and merge this pr

**Comment by YoushaaMurhij** [comment]
I tried this [config ](https://github.com/tianweiy/CenterPoint/blob/new_release/configs/waymo/voxelnet/waymo_centerpoint_voxelnet_three_sweeps_20e_iou_pred.py)but I got this error:
```bash 

  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 126, in main
    train_detector(
  File "/home/trainer/centerpoint/CenterPoint/det3d/torchie/apis/train.py", line 327, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/home/trainer/centerpoint/CenterPoint/det3d/torchie/trainer/trainer.py", line 543, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/home/trainer/centerpoint/CenterPoint/det3d/torchie/trainer/trainer.py", line 395, in train
    for i, data_batch in enumerate(data_loader):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/trainer/centerpoint/CenterPoint/det3d/datasets/waymo/waymo.py", line 92, in __getitem__
    return self.get_sensor_data(idx)
  File "/home/trainer/centerpoint/CenterPoint/det3d/datasets/waymo/waymo.py", line 87, in get_sensor_data
    data, _ = self.pipeline(res, info)
  File "/home/trainer/centerpoint/CenterPoint/det3d/datasets/pipelines/compose.py", line 25, in __call__
    res, info = t(res, info)
  File "/home/trainer/centerpoint/CenterPoint/det3d/datasets/pipelines/preprocess.py", line 290, in __call__
    grid_size = res["lidar"]["voxels"]["shape"]
KeyError: 'voxels'
```
Can you please tell me whatI'm missing?
Thanks.

**Comment by tianweiy** [comment]
I just fixed this issue. It should be runnable now.

**Comment by YoushaaMurhij** [comment]
> I just fixed this issue. It should be runnable now.

Thank you

**Comment by YoushaaMurhij** [comment]
now the model is trainable but we evaluating I got this error:

```bash
 File "tools/dist_test.py", line 211, in <module>
    main()
  File "tools/dist_test.py", line 167, in main
    outputs = batch_processor(
  File "/home/trainer/centerpoint/CenterPoint/det3d/torchie/apis/train.py", line 113, in batch_processor
    return model(example, return_loss=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/trainer/centerpoint/CenterPoint/det3d/models/detectors/voxelnet.py", line 52, in forward
    return self.bbox_head.predict(example, preds, self.test_cfg)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/trainer/centerpoint/CenterPoint/det3d/models/bbox_heads/center_head.py", line 443, in predict
    batch_iou = torch.clamp(batch_iou.reshape(batch, H*W, 1), min=0, max=1)
UnboundLocalError: local variable 'batch_iou' referenced before assignment
```

**Comment by tianweiy** [comment]
fixed

**Comment by hz3014** [comment]
hi, @tianweiy 
I met this FileNotFoundError: [Errno 2] No such file or directory: 'data/Waymo/dbinfos_train_3sweeps_withvelo_painted_final.pkl'
Would you please explain how is this generated? I know there is painted option in CenterPoint/det3d/datasets/pipelines/loading.py
will change paint to true, and sweep=3 in waymo_data_prep , and finally change the file(since current file name is prefixed) name work.

**Comment by tianweiy** [comment]
no need for painted (you can ignore the name, we didn't use pointpainting). Just use sweep=3 and generate the gt database

**Comment by kagecom** [comment]
Hi, can you open-souce the CenterPoint++ code which can reproduce the performance. 

Thanks.

**Pull request closed without merging**
