### PR TITLE
fix bug for direction classifier

### PR DESCRIPTION
**Pull request by qchenclaire**

### CODE REVIEW

**Comment by tianweiy** [comment]
Hi Qi, thanks for the pull request. I would like to ask some further questions in case you have some experience. Do you know which of the following perform the best?

1. cos / sin encoding
2. just raw angle + sin loss + directional classifier
3. cos / sin encoding + directional classifier

I will retrain the models and update the model zoo if the improvement is really large.

**Comment by tianweiy** [comment]
I can confirm directional classifier works quite well now. Thanks for the pull request. I will see if it worths to retrain other models..

**Comment by qchenclaire** [comment]
> Hi Qi, thanks for the pull request. I would like to ask some further questions in case you have some experience. Do you know which of the following perform the best?
> 
> 1. cos / sin encoding
> 2. just raw angle + sin loss + directional classifier
> 3. cos / sin encoding + directional classifier
> 
> I will retrain the models and update the model zoo if the improvement is really large.

I only tried 1 with anchor-free head and 2 with anchor-based head. There is very little difference in mAOE.

**Comment by tianweiy** [comment]
thanks! I am training an anchor-based pp with 2 now. Let's see if it will work better than the cos/sin pp in the model zoo.

**Comment by ZaiwangLi** [comment]
Hi tianweiy and Qi, Have you tried which setting works best?

**Comment by tianweiy** [comment]
I suggest you to use the current version (cos, sin). The directional classifier is a bit complicated.

**Pull request merged**
